apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
#      type: "RollingUpdate"
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
