apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 1234
    protocol: TCP
    nodePort: 31230
    targetPort: 80
  selector:
    app: test
  type: NodePort
status:
  loadBalancer: {}
